default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('DATABASE_USER') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password' } %>
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bugno_development

test:
  <<: *default
  database: bugno_test

production:
  <<: *default
  username: <%= Rails.application.credentials.database_user %>
  password: <%= Rails.application.credentials.database_password %>
  database: <%= Rails.application.credentials.production_database %>
